### PR TITLE
Fixed a few issues that prevent the library (and notebooks) from running in PYNQ 2.4

### PR DESCRIPTION
**Pull request by drichmond**
* Renamed scapy to kamene
* Changed hardcoded site-libraries path to site.getsitepackages()

### CODE REVIEW

**Comment by drichmond** [comment]
I still can't fully run notebook 05

**Comment by yunqu** [comment]
Picked your commit. For the 5th notebook, can you post in the pynq-networking issue tracker? I will also try to make sure the setup.py works fine for the new changes.

**Comment by drichmond** [comment]
Sure, new issue, or old issue?

**Comment by yunqu** [comment]
New issue since it is not related to the kernel module.

**Pull request closed without merging**
